server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ROOT
    url: jdbc:mysql://localhost:3306/xupt_sta?useUnicode&characterEncode=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  mail:
    host: smtp.qq.com
    port: 465
    username:
    password:
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    username:
    password:
    virtual-host:
    host: localhost
    port: 5672
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

