server:
  port: 8084
  ssl:
    protocol: TLS
    key-store: classpath:xuptsta.cn.pfx
    key-store-password: jtsig8k6
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ROOT
    url: jdbc:mysql://139.9.136.188:3306/xupt_sta?useUnicode&characterEncode=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  redis:
    host: 139.9.136.188
    port: 6379
    password: ROOT
    database: 0
  mail:
    host: smtp.qq.com
    port: 465
    username: 3537298158@qq.com
    password: sjqlpfjkgiwkdbjj
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    username: yjc
    password: ROOT
    virtual-host: /yjc
    host: 139.9.136.188
    port: 5672
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

